version: '3'
services: #Collection of Container
    api: #Container 1
        image: catchkapil/fastapi #Rather than building using docker file in prod we pull image from docker hub
        depends_on:
            - postgres
        ports: 
            - 80:8000
        environment:
          - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
          - DATABASE_PORT=${DATABASE_PORT}
          - DATABASE_PASSWORD=${DATABASE_PASSWORD}
          - DATABASE_NAME=${DATABASE_NAME}
          - DATABASE_USERNAME=${DATABASE_USERNAME}
          - SECRET_KEY=${SECRET_KEY}
          - ALGORITHM=${ALGORITHM}
          - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}  
        # volumes:
        #   - ./:/usr/src/app:ro #Binding code on local machine to docker container directory in read only mode   
        # env_file:
        #   - ./.env 
        #command: uvicorn app.main:app --host 0.0.0.0 --port 8000 
    postgres: #Container 2
        image: postgres
        environment:
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
        volumes:
            - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db: